const booksData = [
    {
      id: 1,
      title: "El señor de los anillos",
      author: "J.R.R. Tolkien",
      description: "Una épica novela de fantasía que sigue a un grupo de hobbits en su viaje para destruir el Anillo Único, un artefacto maligno creado por el Señor Oscuro Sauron.",
      genres: ["Fantasía"],
      pages: 1180,
      publisher: "George Allen & Unwin",
      languages: ["Inglés"],
      publicationDate: "1954-1955",
      icon: "Fantasy"
    },
    {
      id: 2,
      title: "La saga de Harry Potter",
      author: "J.K. Rowling",
      description: "Una serie de libros de fantasía que siguen a un joven mago, Harry Potter, y sus amigos mientras asisten al Colegio Hogwarts de Magia y Hechicería y luchan contra el mago oscuro Lord Voldemort.",
      genres: ["Fantasía"],
      pages: "Varía según el libro",
      publisher: "Bloomsbury",
      languages: ["Inglés"],
      publicationDate: "1997-2007",
      icon: "Fantasy"
    },
    {
      id: 3,
      title: "Las crónicas de Narnia",
      author: "C.S. Lewis",
      description: "Una serie de siete libros de fantasía que siguen a los hermanos Pevensie mientras viajan a la tierra mágica de Narnia y luchan contra la Bruja Blanca.",
      genres: ["Fantasía"],
      pages: "Varía según el libro",
      publisher: "Geoffrey Bles",
      languages: ["Inglés"],
      publicationDate: "1950-1956",
      icon: "Fantasy"
    },
    {
      id: 4,
      title: "El juego de Ender",
      author: "Orson Scott Card",
      description: "Una novela de ciencia ficción militar que sigue a Andrew 'Ender' Wiggin, un niño prodigio que es reclutado en una escuela de entrenamiento militar para luchar contra una raza alienígena hostil.",
      genres: ["Ciencia Ficción"],
      pages: 320,
      publisher: "Tor Books",
      languages: ["Inglés"],
      publicationDate: 1985,
      icon: "SciFi"
    },
    {
      id: 5,
      title: "La trilogía de la Materia Oscura",
      author: "Philip Pullman",
      description: "Una serie de novelas de fantasía que siguen a Lyra Belacqua, una niña que viaja a través de universos paralelos para luchar contra una fuerza misteriosa conocida como la Autoridad.",
      genres: ["Fantasía"],
      pages: "Varía según el libro",
      publisher: "Doubleday",
      languages: ["Inglés"],
      publicationDate: "1995-2003",
      icon: "Fantasy"
    },
    {
      id: 6,
      title: "It",
      author: "Stephen King",
      description: "Una novela de terror que sigue a un grupo de siete amigos que se unen para luchar contra una criatura sobrenatural que mata niños en la ciudad de Derry, Maine.",
      genres: ["Terror"],
      pages: 1170,
      publisher: "Viking Press",
      languages: ["Inglés"],
      publicationDate: 1986,
      icon: "Horror"
    },
    {
      id: 7,
      title: "La casa de las hojas",
      author: "Mark Z. Danielewski",
      description: "Una novela de terror experimental que sigue a una familia que se muda a una casa extraña y comienza a experimentar fenómenos paranormales.",
      genres: ["Terror"],
      pages: 707,
      publisher: "Pantheon Books",
      languages: ["Inglés"],
      publicationDate: 2000,
      icon: "Horror"
    },
    {
      id: 8,
      title: "El exorcista",
      author: "William Peter Blatty",
      description: "Una novela de terror sobrenatural que sigue a dos sacerdotes católicos que son llamados para realizar un exorcismo en una niña poseída por un demonio.",
      genres: ["Terror"],
      pages: 496,
      publisher: "Harper & Row",
      languages: ["Inglés"],
      publicationDate: 1971,
      icon: "Horror"
    },
    {
      id: 9,
      title: "El fantasma de la ópera",
      author: "Gaston Leroux",
      description: "Una novela de terror gótica que sigue a la ópera de París, que está siendo perseguida por un fantasma misterioso.",
      genres: ["Terror", "Gótico"],
      pages: 256,
      publisher: "Pierre Lafitte",
      languages: ["Francés"],
      publicationDate: 1910,
      icon: "Horror"
    },
    {
      id: 10,
      title: "Drácula",
      author: "Bram Stoker",
      description: "Una novela de terror gótica que sigue a un joven abogado, Jonathan Harker, que viaja a Transilvania para visitar al Conde Drácula, un vampiro.",
      genres: ["Terror", "Gótico"],
      pages: 120,
      publisher: "Archibald Constable and Company",
      languages: ["Inglés"],
      publicationDate: 1897,
      icon: "Horror"
    },
    {
      id: 11,
      title: "El Silmarillion",
      author: "J.R.R. Tolkien",
      description: "Una obra de mitología y leyenda que relata la creación de la Tierra Media, la Primera y Segunda Edad, y la guerra contra Morgoth.",
      genres: ["Fantasía"],
      pages: 385,
      publisher: "George Allen & Unwin",
      languages: ["Inglés"],
      publicationDate: 1977,
      icon: "Fantasy"
    },
    {
      id: 12,
      title: "La historia interminable",
      author: "Michael Ende",
      description: "Una novela de fantasía que sigue a Bastian Balthazar Bux, un niño que descubre un libro mágico que lo transporta al mundo de Fantasia.",
      genres: ["Fantasía"],
      pages: 264,
      publisher: "K. Thielemann Verlag",
      languages: ["Alemán"],
      publicationDate: 1979,
      icon: "Fantasy"
    },
    {
      id: 13,
      title: "Las Tierras Altas",
      author: "George R.R. Martin",
      description: "Una serie de novelas de fantasía épica que narra las luchas de poder entre varias familias nobles en el continente ficticio de Westeros.",
      genres: ["Fantasía"],
      pages: "Varía según el libro",
      publisher: "HarperCollins",
      languages: ["Inglés"],
      publicationDate: "1996-presente",
      icon: "Fantasy"
    },
    {
      id: 14,
      title: "El nombre del viento",
      author: "Patrick Rothfuss",
      description: "Una novela de fantasía épica que sigue a Kvothe, un mago y músico legendario, mientras relata su historia de vida.",
      genres: ["Fantasía"],
      pages: 662,
      publisher: "DAW Books",
      languages: ["Inglés"],
      publicationDate: 2007,
      icon: "Fantasy"
    },
    {
      id: 15,
      title: "La princesa prometida",
      author: "William Goldman",
      description: "Una novela de fantasía cómica que sigue a Westley, un campesino que debe rescatar a la Princesa Buttercup del malvado Príncipe Humperdinck.",
      genres: ["Fantasía"],
      pages: 224,
      publisher: "Harcourt Brace Jovanovich",
      languages: ["Inglés"],
      publicationDate: 1980,
      icon: "Fantasy"
    },
    {
      id: 16,
      title: "Frankenstein",
      author: "Mary Shelley",
      description: "Una novela de terror gótica que sigue a Victor Frankenstein, un joven científico que crea una criatura a partir de partes de cadáveres.",
      genres: ["Terror", "Gótico"],
      pages: 208,
      publisher: "Lackington, Hurst, Rees, Orme, and Brown",
      languages: ["Inglés"],
      publicationDate: 1818,
      icon: "Horror"
    },
    {
      id: 17,
      title: "El extraño caso del doctor Jekyll y el señor Hyde",
      author: "Robert Louis Stevenson",
      description: "Una novela de terror gótica que sigue a Gabriel John Utterson, un abogado que investiga la doble vida de su amigo, el Dr. Henry Jekyll.",
      genres: ["Terror", "Gótico"],
      pages: 101,
      publisher: "T. Fisher Unwin",
      languages: ["Inglés"],
      publicationDate: 1886,
      icon: "Horror"
    },
    {
      id: 18,
      title: "El misterio de Salem's Lot",
      author: "Stephen King",
      description: "Una novela de terror que sigue a un escritor que se muda a la ciudad de Salem's Lot, Maine, y descubre que la mayoría de los residentes se están convirtiendo en vampiros.",
      genres: ["Terror"],
      pages: 470,
      publisher: "Doubleday",
      languages: ["Inglés"],
      publicationDate: 1975,
      icon: "Horror"
    },
    {
      id: 19,
      title: "Carmesí",
      author: "Clive Barker",
      description: "Una colección de cuentos de terror que incluye historias como 'The Cenobites' y 'The Body'.",
      genres: ["Terror"],
      pages: 352,
      publisher: "Grafton Books",
      languages: ["Inglés"],
      publicationDate: 1985,
      icon: "Horror"
    },
    {
      id: 20,
      title: "Psicosis",
      author: "Robert Bloch",
      description: "Una novela de terror psicológico que sigue a Norman Bates, el dueño de un motel que es perturbado por la personalidad de su madre muerta.",
      genres: ["Terror", "Psicológico"],
      pages: 184,
      publisher: "Simon & Schuster",
      languages: ["Inglés"],
      publicationDate: 1959,
      icon: "Horror"
    },
    {
        id: 1,
        title: "El nombre del viento",
        author: "Patrick Rothfuss",
        description: "La historia de Kvothe, un joven con talento para la magia que busca descubrir la verdad sobre el asesinato de sus padres.",
        genres: ["Fantasía"],
        pages: 880,
        publisher: "DAW Books",
        languages: ["Inglés"],
        publicationDate: 2007,
        icon: "Fantasía"
      },
      {
        id: 2,
        title: "El señor de los anillos: La comunidad del anillo",
        author: "J.R.R. Tolkien",
        description: "El inicio de la épica aventura de Frodo Bolsón para destruir el Anillo Único.",
        genres: ["Fantasía"],
        pages: 480,
        publisher: "Allen & Unwin",
        languages: ["Inglés"],
        publicationDate: 1954,
        icon: "Fantasía"
      },
      {
        id: 3,
        title: "Harry Potter y la piedra filosofal",
        author: "J.K. Rowling",
        description: "El primer libro de la serie de Harry Potter, donde descubre que es un mago y asiste a Hogwarts.",
        genres: ["Fantasía"],
        pages: 223,
        publisher: "Bloomsbury",
        languages: ["Inglés"],
        publicationDate: 1997,
        icon: "Fantasía"
      },
      {
        id: 4,
        title: "Crónica del asesino de reyes: El temor de un hombre sabio",
        author: "Patrick Rothfuss",
        description: "Segunda parte de la historia de Kvothe, profundizando en su aprendizaje y aventuras.",
        genres: ["Fantasía"],
        pages: 1008,
        publisher: "DAW Books",
        languages: ["Inglés"],
        publicationDate: 2011,
        icon: "Fantasía"
      },
      {
        id: 5,
        title: "Canción de hielo y fuego: Juego de tronos",
        author: "George R.R. Martin",
        description: "Primera entrega de la serie, narra las luchas de poder entre las casas nobles de Westeros.",
        genres: ["Fantasía"],
        pages: 694,
        publisher: "Bantam Books",
        languages: ["Inglés"],
        publicationDate: 1996,
        icon: "Fantasía"
      },
      {
        id: 6,
        title: "El hobbit",
        author: "J.R.R. Tolkien",
        description: "La aventura de Bilbo Bolsón para ayudar a un grupo de enanos a recuperar su hogar del dragón Smaug.",
        genres: ["Fantasía"],
        pages: 310,
        publisher: "George Allen & Unwin",
        languages: ["Inglés"],
        publicationDate: 1937,
        icon: "Fantasía"
      },
      {
        id: 7,
        title: "La rueda del tiempo: El ojo del mundo",
        author: "Robert Jordan",
        description: "La primera novela de la serie de fantasía épica 'La rueda del tiempo'.",
        genres: ["Fantasía"],
        pages: 782,
        publisher: "Tor Books",
        languages: ["Inglés"],
        publicationDate: 1990,
        icon: "Fantasía"
      },
      {
        id: 8,
        title: "La trilogía de la materia oscura: Luces del norte",
        author: "Philip Pullman",
        description: "La aventura de Lyra Belacqua en un mundo paralelo lleno de misterio y magia.",
        genres: ["Fantasía"],
        pages: 399,
        publisher: "Scholastic Point",
        languages: ["Inglés"],
        publicationDate: 1995,
        icon: "Fantasía"
      },
      {
        id: 9,
        title: "El camino de los reyes",
        author: "Brandon Sanderson",
        description: "Primera entrega de la serie 'El archivo de las tormentas' donde varios personajes viven sus propias aventuras en un mundo azotado por tormentas.",
        genres: ["Fantasía"],
        pages: 1007,
        publisher: "Tor Books",
        languages: ["Inglés"],
        publicationDate: 2010,
        icon: "Fantasía"
      },
      {
        id: 10,
        title: "El elfo oscuro: La morada",
        author: "R.A. Salvatore",
        description: "La historia del elfo oscuro Drizzt Do'Urden y su lucha por sobrevivir en el inframundo.",
        genres: ["Fantasía"],
        pages: 352,
        publisher: "TSR, Inc.",
        languages: ["Inglés"],
        publicationDate: 1990,
        icon: "Fantasía"
      },
      {
        id: 11,
        title: "El mago de Terramar",
        author: "Ursula K. Le Guin",
        description: "La formación del joven mago Ged en la Escuela de Magia de Roke.",
        genres: ["Fantasía"],
        pages: 183,
        publisher: "Parnassus Press",
        languages: ["Inglés"],
        publicationDate: 1968,
        icon: "Fantasía"
      },
      {
        id: 12,
        title: "La espada de Shannara",
        author: "Terry Brooks",
        description: "Un joven héroe debe encontrar una antigua espada para derrotar a un malvado señor oscuro.",
        genres: ["Fantasía"],
        pages: 726,
        publisher: "Random House",
        languages: ["Inglés"],
        publicationDate: 1977,
        icon: "Fantasía"
      },
      {
        id: 13,
        title: "La canción del suerco",
        author: "Robin Hobb",
        description: "Un joven llamado Fitz se entrena como asesino al servicio de la familia real.",
        genres: ["Fantasía"],
        pages: 448,
        publisher: "Spectra",
        languages: ["Inglés"],
        publicationDate: 1995,
        icon: "Fantasía"
      }
  ];
  
export default booksData;